package com.company;

public enum Category {
    BILLS_AND_UTILITIES,
    CAR_AND_TRANSPORTATION,
    HEALTH,
    INSURANCE,
    GROCERIES,
    SUGARS_AND_JUNKFOOD,
    RESTAURANTS,
    INVESTMENTS,
    ENTERTAINMENT,
    MISC;
}
